service: ${env:SERVICE_NAME}
useDotenv: true

plugins:
  - serverless-esbuild
  - serverless-prune-plugin

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, self:custom.defaultStage}
  region: ap-northeast-1
  memorySize: 256
  timeout: 120
  environment:
    SLACK_SIGNING_SECRET: ${env:SLACK_SIGNING_SECRET}
    SLACK_BOT_USER_OAUTH_TOKEN: ${env:SLACK_BOT_USER_OAUTH_TOKEN}
    SLACK_BOT_MEMBER_ID: ${env:SLACK_BOT_MEMBER_ID}
    OPENAI_RESOURCE: ${env:OPENAI_RESOURCE}
    OPENAI_MODEL_DEPLOY_NAME: ${env:OPENAI_MODEL_DEPLOY_NAME}
    OPENAI_API_KEY: ${env:OPENAI_API_KEY}
    OPENAI_API_VERSION: ${env:OPENAI_API_VERSION}

functions:
  - main:
      handler: src/handler.main
      url: true

custom:
  defaultStage: dev
  prune:
    automatic: true
    number: 3
  esbuild:
    config: "./esbuild.config.js"
